### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gaureshpai** [gaureshpai/Hearease#22]
- [x] Create playlist page with the functionality to be done @gaureshpai 
- [x] list down the requirements of the create playlist page @Dhanya212 @shirha20 
- [x] Functionality of the Player to be changed from play single to play multiple at the same time @gaureshpai 
- [x] display name of the songs playing 
- [x] Logo to be changed @shirha20 
- [x] volume container
- [x] #33
- [x] #34
- [x] More audio to be added to the public/sounds directory @Dhanya212 
- [x] Readme to be edited and done @gaureshpai
